### ISSUE TITLE
Can't run release-fast or release-small WASM binaries.

### ISSUE THREAD

**Issue by Ronsor** [HidamariProject/Hidamari#1]
As the title says, they don't work.
A strange error is received instead:
```
Warning: can't convert to Zig error: no operation found for opcode
```

This is probably a bug in wasm3.

**Comment by vshymanskyy** [comment]
Probably same as https://github.com/wasm3/wasm3/issues/209 (despite a bit different description).
First, suggest upgrading to `0.4.9` to see if there's any improvement.

**Comment by vshymanskyy** [comment]
@Ronsor probably fixed in the latest wasm3 (`main` branch)

**Comment by vshymanskyy** [comment]
@Ronsor could you check the latest version please?

**Comment by Ronsor** [comment]
I've checked that debug WASM binaries work with the latest wasm3.
